'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid = () => crypto.randomUUID ? crypto.randomUUID() : 'id-' + Date.now().toString(36) + Math.random().toString(36).slice(2);
const storageKey = 'underground-workshop-v1';
let state = CraftCore.demo(), selected = null, pending = null, gesture = null, view = {x:0,y:0,scale:1}, modalMode = '', editId = null, draftIcon = '', toastTimer;
try { const saved = localStorage.getItem(storageKey); if (saved) state = CraftCore.validate(JSON.parse(saved)); } catch { setTimeout(() => toast('Сохранение не удалось прочитать. Загружен пример дерева.'), 300); }
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => $('#toast').classList.remove('visible'), 4000); }
function save() { try { localStorage.setItem(storageKey, JSON.stringify(state)); $('#save-status').textContent = '● Сохранено локально'; } catch { $('#save-status').textContent = '● Не сохранено'; toast('Хранилище браузера недоступно или заполнено. Экспортируйте JSON.'); } }
const material = id => state.materials.find(m => m.id === id);
const recipe = id => state.recipes.find(r => r.id === id);
function icon(m, small = false) { return `<span class="item-icon${small ? ' small' : ''}">${m.icon.startsWith('data:image/') ? `<img src="${esc(m.icon)}" alt="">` : esc(m.icon || '◇')}</span>`; }
function renderCatalog() {
  const query = $('#search').value.trim().toLocaleLowerCase('ru');
  $('#recipe-count').textContent = state.recipes.length; $('#material-count').textContent = state.materials.length;
  $('#recipes').innerHTML = state.recipes.filter(r => [r.output,...r.inputs].some(id => material(id).name.toLocaleLowerCase('ru').includes(query))).map(r => `<div class="recipe-card" draggable="true" data-recipe="${esc(r.id)}" tabindex="0" title="Перетащите на поле или нажмите Enter"><button class="card-edit" data-edit-recipe="${esc(r.id)}" aria-label="Изменить рецепт ${esc(material(r.output).name)}">⋯</button>${icon(material(r.output))}<div class="recipe-info"><strong>${esc(material(r.output).name)}</strong><div class="ingredients">${r.inputs.map(id => `<span class="ingredient">${icon(material(id), true)}${esc(material(id).name)}</span>`).join('')}</div></div></div>`).join('') || '<div class="no-results">Рецептов пока нет</div>';
  $('#materials').innerHTML = state.materials.filter(m => m.name.toLocaleLowerCase('ru').includes(query)).map(m => `<button class="material-row" data-material="${esc(m.id)}" title="Изменить: ${esc(m.name)}">${icon(m,true)}<span>${esc(m.name)}</span></button>`).join('') || '<div class="no-results">Материалов пока нет</div>';
}
function renderNodes() {
  $('#nodes').innerHTML = state.nodes.map(n => { const r = recipe(n.recipe), m = material(r.output); return `<article class="node${selected?.id === n.id ? ' selected' : ''}" data-node="${esc(n.id)}" style="left:${n.x}px;top:${n.y}px"><div class="node-header">${icon(m)}<div><div class="node-title">${esc(m.name)}</div><div class="node-subtitle">РЕЦЕПТ КРАФТА</div></div></div><div class="node-body">${r.inputs.map((id,i) => `<div class="port-row"><button class="port" data-node="${esc(n.id)}" data-kind="in" data-input="${i}" title="Вход: ${esc(material(id).name)}" aria-label="Вход: ${esc(material(id).name)}"></button>${icon(material(id),true)}<span>${esc(material(id).name)}</span></div>`).join('')}<div class="port-row output"><span>${esc(m.name)}</span>${icon(m,true)}<button class="port out" data-node="${esc(n.id)}" data-kind="out" title="Выход: ${esc(m.name)}" aria-label="Выход: ${esc(m.name)}"></button></div></div></article>`; }).join('');
  $('#graph-count').textContent = `${state.nodes.length} нод · ${state.edges.length} связей`; $('#empty').hidden = state.nodes.length > 0;
  drawWires();
}
function render() { renderCatalog(); renderNodes(); }
function worldPoint(clientX, clientY) { const rect = $('#canvas').getBoundingClientRect(); return {x:(clientX-rect.left-view.x)/view.scale,y:(clientY-rect.top-view.y)/view.scale}; }
function portPoint(id, kind, input = 0) { const el = [...document.querySelectorAll('.port')].find(p => p.dataset.node === id && p.dataset.kind === kind && (kind === 'out' || +p.dataset.input === input)); if (!el) return {x:0,y:0}; const b = el.getBoundingClientRect(); return worldPoint(b.left+b.width/2,b.top+b.height/2); }
function curve(a,b) { const d = Math.max(65,Math.abs(b.x-a.x)*.45); return `M ${a.x} ${a.y} C ${a.x+d} ${a.y}, ${b.x-d} ${b.y}, ${b.x} ${b.y}`; }
function drawWires(preview) { $('#wires').innerHTML = state.edges.map(e => `<path class="wire${selected?.id === e.id ? ' selected' : ''}" data-edge="${esc(e.id)}" d="${curve(portPoint(e.from,'out'),portPoint(e.to,'in',e.input))}"/>`).join(''); if (pending && preview) { const a = portPoint(pending.node,pending.kind,pending.input); $('#wires').innerHTML += `<path class="wire preview" d="${pending.kind === 'out' ? curve(a,preview) : curve(preview,a)}"/>`; } }
function applyView() { $('#world').style.transform = `translate(${view.x}px,${view.y}px) scale(${view.scale})`; $('#zoom-value').textContent = Math.round(view.scale*100)+'%'; $('#canvas').style.backgroundSize = `${22*view.scale}px ${22*view.scale}px`; $('#canvas').style.backgroundPosition = `${view.x}px ${view.y}px`; }
function zoom(factor, cx, cy) { const rect = $('#canvas').getBoundingClientRect(); cx ??= rect.left+rect.width/2; cy ??= rect.top+rect.height/2; const p = worldPoint(cx,cy); view.scale = Math.max(.25,Math.min(2,view.scale*factor)); view.x = cx-rect.left-p.x*view.scale; view.y = cy-rect.top-p.y*view.scale; applyView(); }
function fit() { if (!state.nodes.length) {view={x:0,y:0,scale:1};applyView();return;} const minX=Math.min(...state.nodes.map(n=>n.x)), minY=Math.min(...state.nodes.map(n=>n.y)), maxX=Math.max(...state.nodes.map(n=>n.x+236)), maxY=Math.max(...state.nodes.map(n=>n.y+245)); const b=$('#canvas').getBoundingClientRect();view.scale=Math.max(.25,Math.min(1,(b.width-90)/(maxX-minX),(b.height-115)/(maxY-minY)));view.x=(b.width-(maxX-minX)*view.scale)/2-minX*view.scale;view.y=(b.height-(maxY-minY)*view.scale)/2-minY*view.scale;applyView();drawWires(); }
function addNode(id,p) { if(!recipe(id))return; const n={id:uid(),recipe:id,x:p.x,y:p.y};state.nodes.push(n);selected={type:'node',id:n.id};renderNodes();save(); }
$('#search').addEventListener('input',renderCatalog);
$('#recipes').addEventListener('dragstart',e=>{const card=e.target.closest('[data-recipe]');if(card){e.dataTransfer.setData('text/plain',card.dataset.recipe);e.dataTransfer.effectAllowed='copy';}});
$('#recipes').addEventListener('keydown',e=>{if(e.key==='Enter' && e.target.matches('.recipe-card')){const b=$('#canvas').getBoundingClientRect();addNode(e.target.dataset.recipe,worldPoint(b.left+b.width/2-118,b.top+b.height/2-100));}});
$('#recipes').addEventListener('click',e=>{const edit=e.target.closest('[data-edit-recipe]');if(edit)openRecipe(edit.dataset.editRecipe);});
$('#materials').addEventListener('click',e=>{const row=e.target.closest('[data-material]');if(row)openMaterial(row.dataset.material);});
const canvas=$('#canvas');
canvas.addEventListener('dragover',e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';canvas.classList.add('dragover');});
canvas.addEventListener('dragleave',()=>canvas.classList.remove('dragover'));
canvas.addEventListener('drop',e=>{e.preventDefault();canvas.classList.remove('dragover');const p=worldPoint(e.clientX,e.clientY);addNode(e.dataTransfer.getData('text/plain'),{x:p.x-118,y:p.y-35});});
function clearPending(){pending=null;document.querySelectorAll('.port.pending').forEach(p=>p.classList.remove('pending'));drawWires();}
function connectPort(port){const target={node:port.dataset.node,kind:port.dataset.kind,input:+port.dataset.input};if(!pending){pending=target;port.classList.add('pending');toast('Выберите коннектор с таким же материалом на другой ноде.');return;}if(pending.node===target.node&&pending.kind===target.kind){clearPending();return;}if(pending.kind===target.kind){toast('Соедините выход с входом.');return;}const from=pending.kind==='out'?pending:target,to=pending.kind==='in'?pending:target;const error=CraftCore.connectionError(state,from.node,to.node,to.input);if(error){toast(error);return;}state.edges.push({id:uid(),from:from.node,to:to.node,input:to.input});clearPending();renderNodes();save();}
canvas.addEventListener('pointerdown',e=>{if(e.button!==0||e.target.closest('.zoom-controls'))return;canvas.focus();const port=e.target.closest('.port');if(port){e.preventDefault();connectPort(port);return;}const edge=e.target.closest('[data-edge]');if(edge){selected={type:'edge',id:edge.dataset.edge};renderNodes();return;}const node=e.target.closest('.node');selected=node?{type:'node',id:node.dataset.node}:null;document.querySelectorAll('.node').forEach(n=>n.classList.toggle('selected',n.dataset.node===selected?.id));drawWires();if(node&&!e.target.closest('.node-header'))return;const n=node?state.nodes.find(n=>n.id===node.dataset.node):null;gesture={type:n?'node':'pan',node:n,startX:e.clientX,startY:e.clientY,x:n?n.x:view.x,y:n?n.y:view.y};canvas.setPointerCapture(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(gesture){const dx=e.clientX-gesture.startX,dy=e.clientY-gesture.startY;if(gesture.type==='node'){gesture.node.x=gesture.x+dx/view.scale;gesture.node.y=gesture.y+dy/view.scale;const el=[...document.querySelectorAll('.node')].find(n=>n.dataset.node===gesture.node.id);el.style.left=gesture.node.x+'px';el.style.top=gesture.node.y+'px';drawWires();}else{view.x=gesture.x+dx;view.y=gesture.y+dy;applyView();}}else if(pending)drawWires(worldPoint(e.clientX,e.clientY));});
function endGesture(){if(gesture?.type==='node')save();gesture=null;}
canvas.addEventListener('pointerup',endGesture);canvas.addEventListener('pointercancel',endGesture);
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.1:1/1.1,e.clientX,e.clientY);},{passive:false});
$('#zoom-in').onclick=()=>zoom(1.2);$('#zoom-out').onclick=()=>zoom(1/1.2);$('#fit').onclick=fit;
document.addEventListener('keydown',e=>{if($('#modal').open||e.target.matches('input,select,textarea'))return;if(e.key==='Escape')clearPending();if((e.key==='Delete'||e.key==='Backspace')&&selected){e.preventDefault();if(selected.type==='node'){state.nodes=state.nodes.filter(n=>n.id!==selected.id);state.edges=state.edges.filter(x=>x.from!==selected.id&&x.to!==selected.id);}else state.edges=state.edges.filter(x=>x.id!==selected.id);selected=null;clearPending();renderNodes();save();}});
$('#clear').onclick=()=>{if(state.nodes.length&&confirm('Удалить все ноды и связи? Материалы и рецепты останутся.')){state.nodes=[];state.edges=[];selected=null;clearPending();renderNodes();save();}};
function options(value,optional=false){return (optional?'<option value="">Не требуется</option>':'<option value="" disabled selected>Выберите материал</option>')+state.materials.map(m=>`<option value="${esc(m.id)}" ${m.id===value?'selected':''}>${esc(m.name)}</option>`).join('');}
function uploadMarkup(){return `<div class="upload-area"><div id="icon-preview"></div><div><button type="button" id="pick-icon">↥ Загрузить иконку</button> <button type="button" id="paste-icon">Вставить</button></div><p>PNG, JPG, WebP, GIF · до 5 МБ<br>Также можно вставить изображение через Ctrl+V</p><input type="file" id="icon-file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></div>`;}
function initModal(title){$('#modal-title').textContent=title;$('#form-error').textContent='';$('#modal-form button[type="submit"]').hidden=false;$('#modal').showModal();}
function openMaterial(id=null){modalMode='material';editId=id;const m=id?material(id):null;draftIcon=m?.icon||'◇';$('#modal-body').innerHTML=`<label class="field">Название материала<input id="material-name" maxlength="100" required placeholder="Например, медная руда" value="${esc(m?.name||'')}"></label>${uploadMarkup()}<p class="form-note">Материал появится в списке и станет доступен для рецептов.</p>`;initModal(id?'Изменить материал':'Новый материал');bindUpload();$('#material-name').focus();}
function openRecipe(id=null){if(!state.materials.length){toast('Сначала добавьте материалы.');openMaterial();return;}modalMode='recipe';editId=id;const r=id?recipe(id):null;draftIcon='';$('#modal-body').innerHTML=`<label class="field">Результат крафта<select id="output-material" required>${options(r?.output)}</select></label><label class="field">Входящий материал 1<select id="input-one" required>${options(r?.inputs[0])}</select></label><label class="field">Входящий материал 2 <span class="form-note">· необязательно</span><select id="input-two">${options(r?.inputs[1],true)}</select></label>${uploadMarkup()}<p class="form-note">Иконка относится к материалу результата и обновится во всём каталоге.</p>`;initModal(id?'Изменить рецепт':'Новый рецепт');bindUpload();$('#output-material').onchange=()=>{draftIcon='';updatePreview();};}
function updatePreview(){const m=modalMode==='recipe'?material($('#output-material').value):null;$('#icon-preview').innerHTML=icon({icon:draftIcon||m?.icon||'◇'});}
async function loadIcon(file){if(!file||!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type))throw Error('Выберите изображение PNG, JPG, WebP или GIF.');if(file.size>5*1024*1024)throw Error('Размер файла не должен превышать 5 МБ.');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');const scale=Math.min(1,128/Math.max(img.width,img.height));c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);draftIcon=c.toDataURL('image/png');updatePreview();}finally{URL.revokeObjectURL(url);}}
function bindUpload(){updatePreview();$('#pick-icon').onclick=()=>$('#icon-file').click();$('#icon-file').onchange=async e=>{try{await loadIcon(e.target.files[0]);}catch(err){$('#form-error').textContent=err.message;}};$('#paste-icon').onclick=async()=>{try{if(!navigator.clipboard?.read)throw Error();const items=await navigator.clipboard.read();const item=items.find(i=>i.types.some(t=>t.startsWith('image/')));if(!item){$('#form-error').textContent='В буфере нет изображения.';return;}await loadIcon(await item.getType(item.types.find(t=>t.startsWith('image/'))));}catch{$('#form-error').textContent='Нажмите Ctrl+V в этом окне или загрузите файл.';}};}
document.addEventListener('paste',async e=>{if(!$('#modal').open||!['recipe','material'].includes(modalMode))return;const item=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'));if(item){e.preventDefault();try{await loadIcon(item.getAsFile());}catch(err){$('#form-error').textContent=err.message;}}});
$('#modal-form').onsubmit=e=>{e.preventDefault();if(modalMode==='material'){const name=$('#material-name').value.trim();if(!name){$('#form-error').textContent='Введите название материала.';return;}if(state.materials.some(m=>m.id!==editId&&m.name.toLocaleLowerCase()===name.toLocaleLowerCase())){$('#form-error').textContent='Материал с таким названием уже существует.';return;}if(editId)Object.assign(material(editId),{name,icon:draftIcon});else state.materials.push({id:uid(),name,icon:draftIcon});}else if(modalMode==='recipe'){const output=$('#output-material').value,inputs=[$('#input-one').value,$('#input-two').value].filter(Boolean);if(!output||!inputs.length||inputs.includes(output)||new Set(inputs).size!==inputs.length){$('#form-error').textContent='Выберите результат и один или два разных входящих материала. Результат не может быть входом.';return;}if(editId){Object.assign(recipe(editId),{output,inputs});const old=state.edges;state.edges=[];for(const edge of old)if(!CraftCore.connectionError(state,edge.from,edge.to,edge.input))state.edges.push(edge);if(old.length!==state.edges.length)toast('Несовместимые связи изменённого рецепта удалены.');}else state.recipes.push({id:uid(),output,inputs});if(draftIcon)material(output).icon=draftIcon;}$('#modal').close();clearPending();render();save();};
$('#add-material').onclick=()=>openMaterial();$('#add-recipe').onclick=()=>openRecipe();$('#close-modal').onclick=$('#cancel-modal').onclick=()=>$('#modal').close();
$('#help-button').onclick=()=>{modalMode='help';$('#modal-body').innerHTML='<p class="form-note">1. Добавьте материалы и их иконки.<br><br>2. Создайте рецепт: один результат и до двух входящих материалов.<br><br>3. Перетащите рецепт на поле. Также можно выбрать его клавишей Tab и нажать Enter.<br><br>4. Нажмите на кружок выхода справа, затем на кружок подходящего входа слева. Материалы должны совпадать.<br><br>5. Перетаскивайте ноды за заголовок, а поле — за свободное место. Колесо изменяет масштаб.<br><br>6. Выделите ноду или линию и нажмите Delete для удаления. Esc отменяет создание связи.<br><br>Изменение материала: нажмите на него в каталоге. Изменение рецепта: кнопка «⋯».<br><br>Все изменения сохраняются в этом браузере. Экспорт JSON сохраняет материалы, иконки, рецепты, ноды и связи в одном файле.</p>';initModal('Как пользоваться');$('#modal-form button[type="submit"]').hidden=true;};
$('#export-button').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='workshop-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Дерево экспортировано в JSON.');};
$('#import-button').onclick=()=>$('#import-file').click();
$('#import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20*1024*1024)throw Error('JSON-файл не должен превышать 20 МБ.');const next=CraftCore.validate(JSON.parse(await file.text()));if(!confirm('Заменить текущую мастерскую данными из файла? Сначала экспортируйте текущую, если хотите сохранить её.'))return;state=next;selected=null;pending=null;render();fit();save();toast('Мастерская загружена.');}catch(err){toast(err instanceof SyntaxError?'Файл не содержит корректный JSON.':err.message);}finally{e.target.value='';}};
render();requestAnimationFrame(fit);window.addEventListener('resize',()=>{applyView();drawWires();});
